blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/autowarefoundation/autoware/discussions/new?category=q-a
    about: Ask a question

  - name: Idea
    url: https://github.com/autowarefoundation/autoware/discussions/new?category=ideas
    about: Post an idea

  - name: Request
    url: https://github.com/autowarefoundation/autoware/discussions/new?category=requests
    about: Send a request
